BTL_Nhom11/Areas/Admin/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom11.Areas.Admin.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Admin/Accounts
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit()
        {
            return View();
        }
    }
}

BTL_Nhom11/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom11.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Admin/Categories
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit()
        {
            return View();
        }
    }
}

BTL_Nhom11/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom11.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Category()
        {
            return View();
        }
        public ActionResult Product()
        {
            return View();
        }
        public ActionResult Order()
        {
            return View();
        }
        public ActionResult Account()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
    }
}

BTL_Nhom11/Areas/Admin/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom11.Areas.Admin.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Admin/Orders
        public ActionResult Edit()
        {
            return View();
        }
    }
}

BTL_Nhom11/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom11.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Admin/Products
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Detail()
        {
            return View();
        }
        public ActionResult Edit()
        {
            return View();
        }
        
    }
}

BTL_Nhom11/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom11.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductList()
        {
            return View();
        }
        public ActionResult ProductDetail()
        {
            return View();
        }
        public ActionResult Card()
        {
            return View();
        }
        public ActionResult Order()
        {
            return View();
        }
        public ActionResult DetailOrder()
        {
            return View();
        }
        public ActionResult Account()
        {
            return View();
        }
        public ActionResult ChangePass()
        {
            return View();
        }
        public ActionResult EditAccount()
        {
            return View();
        }
    }
}

BTL_Nhom11/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom11.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult Logout()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

BTL_Nhom11/Areas/Admin/Views/Home/Account.cshtml
@{
    ViewBag.Title = "Account";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">

    <div class="contain_2 container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-12 mb-3">
                    <h2 class="page-title">Quản Lý Tài Khoản</h2>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <!--Content-->
        <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-2">
                <div class="table-data__tool pu">

                    <div class="table-data__tool-right">
                        <a href="@Url.Action("Create","Accounts")">
                            <button class="au-btn ">
                                Thêm  <i class="fas fa-plus"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="table-responsive table--no-card">
                <table class="table table-borderless table-striped table-earning">
                    <thead class="title-cate">
                        <tr>
                    <thead>
                        <tr>
                            <th>Mã TK</th>
                            <th>Tên Đăng Nhập</th>
                            <th>Mật Khẩu</th>
                            <th>Họ Tên</th>
                            <th>SĐT</th>
                            <th>Email</th>
                            <th>Quyền</th>
                            <th>Họat Động</th>
                        </tr>
                    </thead>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>admin</td>
                            <td>******</td>
                            <td>Nguyễn Văn A</td>
                            <td>0334334334</td>
                            <td>abc@gmail.com</td>
                            <td>admin</td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Edit","Accounts")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td> namdv </td>
                            <td>******</td>
                            <td>Nguyễn Văn B</td>
                            <td>0334333323</td>
                            <td>nam@gmail.com</td>
                            <td>admin</td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Edit","Accounts")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>thuht</td>
                            <td>******</td>
                            <td>Hoàng Thị T</td>
                            <td>0334332242</td>
                            <td>abc@gmail.com</td>
                            <td>user</td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Edit","Accounts")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>









                        <!-- Xác nhận xoá -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Xác nhận xoá?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Bạn có muốn xoá bản ghi này ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                        <button type="button" class="btn btn-info">Đồng ý</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </tbody>
                </table>
            </div>
        </div>

        <!--end content-->

    </div>
</div>

BTL_Nhom11/Areas/Admin/Views/Home/Category.cshtml
@{
    ViewBag.Title = "Category";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">

    <div class="contain_2 container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-12 mb-3">
                    <h2 class="page-title">Quản Lý Danh Mục</h2>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <!--Content-->
        <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-2">
                <div class="table-data__tool pu">

                    <div class="table-data__tool-right">
                        <button class="au-btn ">
                            @Html.ActionLink("Thêm", "Create", "Categories")
                                  <i class="fas fa-plus"></i>
                           
                        </button>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="table-responsive table--no-card">
                <table class="table table-borderless table-striped table-earning">
                    <thead class="title-cate">
                        <tr>
                    <thead>
                        <tr>
                            <th>Mã Danh Mục</th>
                            <th>Tên Danh Mục</th>
                            <th>Hoạt Động</th>
                        </tr>
                    </thead>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>
                                <span class="block-email">Bút - Viết</span>
                            </td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Edit","Categories")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>
                                <span class="block-email">Dụng Cụ Học Sinh</span>
                            </td>
                            <td>
                                <div class="table-data-feature">

                                    <a class="item" href="@Url.Action("Edit","Categories")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>
                                <span class="block-email">Sản Phẩm Về Giấy</span>
                            </td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Edit","Categories")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>
                                <span class="block-email">Dụng Cụ Văn Phòng</span>
                            </td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="suadanhmuc.html" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>
                                <span class="block-email">Dụng Cụ Vẽ</span>
                            </td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Edit","Categories")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>


                        <!-- Xác nhận xoá -->
                        @{
                            Html.RenderPartial("Delete");
                        }



                    </tbody>
                </table>
            </div>
        </div>

        <!--end content-->

    </div>
</div>

BTL_Nhom11/Areas/Admin/Views/Home/Order.cshtml
@{
    ViewBag.Title = "Order";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">

    <div class="contain_2 container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-12 mb-3">
                    <h2 class="page-title">Quản Lý Đơn Hàng</h2>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <!--Content-->

        <div class="row">
            <div class="table-responsive table--no-card table-product">
                <table class="table table-borderless table-striped table-earning">
                    <thead class="title-cate">
                        <tr>
                    <thead>
                        <tr>
                            <th>Mã ĐH</th>
                            <th>Mã KH</th>
                            <th>Tên Khách Hàng</th>
                            <th>SĐT</th>
                            <th>Địa Chỉ</th>
                            <th>Tổng Tiền</th>
                            <th>Ngày Đặt</th>
                            <th>Tình Trạng</th>

                            <th>Hoạt Động</th>
                        </tr>
                    </thead>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>0001</td>
                            <td>005</td>
                            <td>Nguyễn Văn A</td>
                            <td>0334144012</td>
                            <td>134/22 Cầu Diễn - Hà Nội</td>
                            <td>100000</td>
                            <td>8/10/2021</td>
                            <td>Đã Giao</td>
                            <td>
                                <div class="table-data-feature">

                                    <a class="item" href="@Url.Action("Edit","Orders")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>0002</td>
                            <td>0008</td>
                            <td>Nguyễn Văn B</td>
                            <td>0334144012</td>
                            <td>134/22 Cầu Diễn - Hà Nội</td>
                            <td>210000</td>
                            <td>8/10/2021</td>
                            <td>Đã Giao</td>
                            <td>
                                <div class="table-data-feature">

                                    <a class="item" href="@Url.Action("Edit","Orders")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>0003</td>
                            <td>0009</td>
                            <td>Nguyễn Văn C</td>
                            <td>0334143333</td>
                            <td>134/22 Đại Học Công Nghiệp Hà Nội</td>
                            <td>50000</td>
                            <td>8/10/2021</td>
                            <td>Đang xác nhận</td>
                            <td>
                                <div class="table-data-feature">

                                    <a class="item" href="@Url.Action("Edit","Orders")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>

                        <!-- Xác nhận xoá -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Xác nhận xoá?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Bạn có muốn xoá bản ghi này ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                        <button type="button" class="btn btn-info">Đồng ý</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </tbody>
                </table>
            </div>
        </div>

        <!--end content-->

    </div>
</div>

BTL_Nhom11/Areas/Admin/Views/Home/Product.cshtml
@{
    ViewBag.Title = "Product";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper ">

    <div class="contain_2 container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-12 mb-3">
                    <h2 class="page-title">Quản Lý Sản Phẩm</h2>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <!--Content-->
        <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-2">
                <div class="table-data__tool pu">

                    <div class="table-data__tool-right">
                        <button class="au-btn ">
                            <a href="@Url.Action("Create","Products")">
                                Thêm  <i class="fas fa-plus"></i>
                            </a>
                        </button>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="table-responsive table--no-card table-product">
                <table class="table table-borderless table-striped table-earning">
                    <thead class="title-cate">
                        <tr>
                    <thead>
                        <tr>
                            <th>Mã Sản Phẩm</th>
                            <th>Tên Sản Phẩm</th>
                            <th>Tên Danh Mục</th>
                            <th>Giá Tiền</th>
                            <th>Số Lượng</th>

                            <th>Hoạt Động</th>
                        </tr>
                    </thead>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>
                                <span class="block-email"><img src="~/Areas/Admin/Assets/images/sanpham/8802203035948_1.jpg" alt="ruột bút" width="50px"> Ruột Chì HQ 502</span>
                            </td>
                            <td>Dụng cụ học sinh</td>
                            <td>8000</td>
                            <td>50</td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Detail","Products")" data-toggle="tooltip" data-placement="top" title="Xem chi tiết">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a class="item" href="@Url.Action("Edit","Products")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>
                                <span class="block-email"><img src="~/Areas/Admin/Assets/images/sanpham/image_195509_1_3137.jpg" alt="bút viết" width="50px"> Bút Bi 0.5 mm Treeden</span>
                            </td>
                            <td>Bút-Viết</td>
                            <td>3000</td>
                            <td>200</td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Detail","Products")" data-toggle="tooltip" data-placement="top" title="Xem chi tiết">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a class="item" href="@Url.Action("Edit","Products")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>
                                <span class="block-email"><img src="~/Areas/Admin/Assets/images/sanpham/image_195509_1_40535.jpg" alt="bút" width="50px"> Viết Nước My-Gel Đông A - Mực Đỏ</span>
                            </td>
                            <td>Bút-Viết</td>
                            <td>20000</td>
                            <td>40</td>
                            <td>
                                <div class="table-data-feature">
                                    <a class="item" href="@Url.Action("Detail","Products")" data-toggle="tooltip" data-placement="top" title="Xem chi tiết">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a class="item" href="@Url.Action("Edit","Products")" data-toggle="tooltip" data-placement="top" title="Sửa">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="item" data-placement="top" title="Xóa" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>














                        <!-- Xác nhận xoá -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Xác nhận xoá?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Bạn có muốn xoá bản ghi này ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                        <button type="button" class="btn btn-info">Đồng ý</button>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </tbody>
                </table>
            </div>
        </div>

        <!--end content-->

    </div>
</div>